### ISSUE TITLE
Set max line length for lll linter from configuration

### ISSUE THREAD

**Issue by bzz** [src-d/lookout-gometalint-analyzer#5]
So if in local `.lookout.yaml` (or global server configuration) include

```
analyzers:
  - name: gometalint-analyzer
     linters:
       - name: lll
         maxLen: 120

```

[lll](https://github.com/alecthomas/gometalinter#supported-linters) linter should report only lines more the 120 chars. 
Simplest way to do so is by passing this as `--line-length=N` CLI args to `lll`.

This would allow to remove some friction, while using it.

**Comment by smacker** [comment]
config will be:

```
analyzers:
  - name: gometalint-analyzer
    settings:
      linters:
       - name: lll
         maxLen: 120
```

because the configuration must be inside `settings` in lookout
